{
 "title": "Hello O2",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hello_world_server_requests_total[5m]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Request Rate by Endpoints",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hello_world_server_requests_total[5m])) by (path)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Request Rate by Pod",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hello_world_server_requests_total[5m])) by (pod)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "hello_world_server_requests_total (counter)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hello_world_server_requests_total"
    }
   ]
  }
 ]
}